#!/bin/bash -e

# created config file
export ZABBIX_SERVER_HOST=${ZABBIX_SERVER_HOST:-${ZABBIX_PORT_10051_TCP_ADDR}}
export ZABBIX_SERVER_NAME=${ZABBIX_SERVER_NAME:-}
export ZABBIX_SERVER_PORT=${ZABBIX_SERVER_PORT:-10051}
export ZABBIX_DB_HOST=${ZABBIX_DB_HOST:-${DB_PORT_3306_TCP_ADDR}}
export ZABBIX_DB_PORT=${ZABBIX_DB_PORT:-3306}
export ZABBIX_DB_NAME=${ZABBIX_DB_NAME:-zabbix}
export ZABBIX_DB_USER=${ZABBIX_DB_USER:-root}
export ZABBIX_DB_PASSWORD=${ZABBIX_DB_PASSWORD:-}
export CONFD_BACKEND=${CONFD_BACKEND:-env}
confd -onetime -backend ${CONFD_BACKEND}

apache2ctl start

tail -f
